import { Product } from "@/types/product";

const now = new Date().toISOString();

export const MOCK_PRODUCTS: Product[] = [
  {
    _id: "1",
    slug: "oversized-denim-jacket",
    title: "Oversized Denim Jacket",
    description: "A relaxed-fit denim jacket with a faded wash.",
    images: ["/products/denim-jacket.jpg"],
    price: 129,
    discount: 20,
    rating: 4.5,
    numReviews: 42,
    stock: 18,
    category: "Jackets",
    colors: ["Navy", "Black"],
    sizes: ["S", "M", "L", "XL"],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "2",
    slug: "classic-white-tee",
    title: "Classic White Tee",
    description: "A soft, everyday cotton tee.",
    images: ["/products/white-tee.jpg"],
    price: 35,
    discount: 0,
    rating: 4.2,
    numReviews: 87,
    stock: 60,
    category: "T-Shirts",
    colors: ["White", "Black"],
    sizes: ["XS", "S", "M", "L"],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "3",
    slug: "aviator-street-hoodie",
    title: "Aviator Street Hoodie",
    description: "A heavyweight hoodie built for cold mornings.",
    images: ["/products/hoodie.jpg"],
    price: 89,
    discount: 15,
    rating: 4.7,
    numReviews: 23,
    stock: 12,
    category: "Hoodies",
    colors: ["Grey", "Black", "Brown"],
    sizes: ["M", "L", "XL", "XXL"],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "4",
    slug: "tailored-red-shirt",
    title: "Tailored Red Shirt",
    description: "A crisp tailored shirt for formal occasions.",
    images: ["/products/red-shirt.jpg"],
    price: 65,
    discount: 5,
    rating: 4.0,
    numReviews: 15,
    stock: 30,
    category: "Shirts",
    colors: ["Red", "Black"],
    sizes: ["S", "M", "L"],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "5",
    slug: "slim-fit-denim-jeans",
    title: "Slim Fit Denim Jeans",
    description: "Slim fit jeans with a slight stretch.",
    images: ["/products/jeans.jpg"],
    price: 95,
    discount: 0,
    rating: 4.4,
    numReviews: 51,
    stock: 22,
    category: "Jeans",
    colors: ["Denim", "Black"],
    sizes: ["S", "M", "L", "XL"],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "6",
    slug: "olive-cargo-shorts",
    title: "Olive Cargo Shorts",
    description: "Utility cargo shorts with multiple pockets.",
    images: ["/products/shorts.jpg"],
    price: 55,
    discount: 10,
    rating: 3.9,
    numReviews: 9,
    stock: 40,
    category: "Shorts",
    colors: ["Olive", "Beige"],
    sizes: ["S", "M", "L", "XL"],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "7",
    slug: "party-satin-shirt",
    title: "Party Satin Shirt",
    description: "A statement satin shirt for nights out.",
    images: ["/products/satin-shirt.jpg"],
    price: 110,
    discount: 0,
    rating: 4.6,
    numReviews: 7,
    stock: 10,
    category: "Shirts",
    colors: ["Pink", "Black"],
    sizes: ["M", "L", "XL"],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: "8",
    slug: "performance-training-hoodie",
    title: "Performance Training Hoodie",
    description: "A moisture-wicking hoodie built for training days.",
    images: ["/products/training-hoodie.jpg"],
    price: 78,
    discount: 0,
    rating: 4.3,
    numReviews: 34,
    stock: 25,
    category: "Hoodies",
    colors: ["Black", "Grey"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    createdAt: now,
    updatedAt: now,
  },
];
